Import/export schema processes (#5269)
* add missing methods to CMIS interfaces

* expose method for document creation without VersioningState

consider to deprecate the old one

* remove ts function

* add system BPM processes bootstrap logic

* WIP: processes REST endpoints, triggers, json context, wrappers etc/

* WIP: topology task

* WIP: topology task

* WIP: topology task refactoring

* WIP: save export topology

* save export topology in file

* fix issue

* fix api

* store primitive wrappers and strings as they are, everything else as json, WIP: multi-instance task for table export

* add support simple collections variable value in flowable

collections: set, list, queue
element types: primitive wrappers, booleans and strings

* wip: export table definition task

* refactoring

* refactoring

* export tables data task to csv

* fix table.toString related NPE exceptions

* wip, refactoring, import, skeleton, load topology, etc.

* wip: import schema process

* wip

* wip

* wip: set unique for columns

* wip: skip creating unique indexes when columns are already marked as unique

* wip: skip check constraints creation when there is no expression exported

* wip: export default value as well

* wip: add support for auto increment columns

* wip: fix tests

* wip: fix binary export issue

* wip: fix import issues - align export csv format with the import csv format

preventing errors like:
Caused by: org.apache.commons.csv.CSVException: Invalid character between encapsulated token and delimiter at line: 6, position: 412
	at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:370) ~[commons-csv-1.14.1.jar!/:1.14.1]
	at org.apache.commons.csv.Lexer.nextToken(Lexer.java:294) ~[commons-csv-1.14.1.jar!/:1.14.1]
	at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:892) ~[commons-csv-1.14.1.jar!/:1.14.1]
	at org.apache.commons.io.function.Uncheck.get(Uncheck.java:213) ~[commons-io-2.20.0.jar!/:2.20.0]
	... 40 common frames omitted

* wip: align tenant status type with the other enums from the artifact

* wip: fix export of tables with multiple FKs - export as once FK entry

prevent import issues - tries to create multiple FK constrains with the same name (should be once constraint)

example table QRTZ_TRIGGERS:
https://github.com/quartz-scheduler/quartz/blob/5fd9d6b1bb8b0629abe38543f45aee392c0ca937/quartz/src/main/resources/org/quartz/impl/jdbcjobstore/tables_h2.sql#L237

* align type columns with the other enums from the artifact

* format the code

* fix importing values with empty string values

org.h2.jdbc.JdbcBatchUpdateException: NULL not allowed for column "JOB_CLASS"; SQL statement:
INSERT INTO "DIRIGIBLE_JOBS" ("JOB_ID", "CREATED_AT", "CREATED_BY", "UPDATED_AT", "UPDATED_BY", "ARTEFACT_DEPENDENCIES", "ARTEFACT_DESCRIPTION", "ARTEFACT_ERROR", "ARTEFACT_KEY", "ARTEFACT_STATUS", "ARTEFACT_LOCATION", "ARTEFACT_NAME", "ARTEFACT_PHASE", "ARTEFACT_RUNNING", "ARTEFACT_TYPE", "JOB_CLASS", "JOB_ENABLED", "JOB_ENGINE", "JOB_EXECUTED_AT", "JOB_EXPRESSION", "JOB_GROUP", "JOB_HANDLER", "JOB_MESSAGE", "JOB_SINGLETON", "JOB_STATUS") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23502-232]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1277) ~[h2-2.3.232.jar!/:na]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-6.3.0.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-6.3.0.jar!/:na]
	at org.eclipse.dirigible.components.data.csvim.processor.CsvProcessor.insert(CsvProcessor.java:113) ~[dirigible-components-data-csvim-13.0.0-SNAPSHOT.jar!/:na]

* fix topology export - export dependenices in depth

* fix export/import of composite (columns > 1) unique constraints

* export/import empty strings as "" in CSV to distinguish it from nulls

This way empty strings are correctly exported and imported back.

Until now, nulls and empty strings were treated either as "" or as null (depending on config)

* fix reported issues

* execute tasks for the registered tenant

* add skip task implementation logic like in JSTask

* add simple support for enum types - map enums to nvarchar

* return enum columns in Job.java, JobLog.java, Tenant.java

* use more unique task bean names to prevent possible further collisions

* Add export/import integration test

a simple export/import of systemdb

* format

* fix log

* fix some issues related to import in postgresql

* add advanced integration test

* fix creating tables in schema != of the datasource default

* fix SchemaExportImportIT - create target schema for postgresql

since PUBLIC schema doesn't exist by default

* change import schema determination logic

it doesn't work correctly for Postgres

25-09-09T13:40:05.5978940Z 2025-09-09 13:40:05.429 [ERROR] [flowable-async-job-executor-thread-3] [background] o.f.c.e.i.interceptor.CommandContext - Error while closing command context
2025-09-09T13:40:05.5981286Z org.eclipse.dirigible.components.data.processes.schema.imp.tasks.SchemaImportException: Failed to import data into table [USERS] from document with path [/export-folder/USERS.csv]
2025-09-09T13:40:05.5983581Z 	at org.eclipse.dirigible.components.data.processes.schema.imp.tasks.ImportTableDataTask.execute(ImportTableDataTask.java:42) ~[dirigible-components-data-processes-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.5985446Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
2025-09-09T13:40:05.5986482Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
2025-09-09T13:40:05.5987639Z 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359) ~[spring-aop-6.2.7.jar:6.2.7]
2025-09-09T13:40:05.5989424Z 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:724) ~[spring-aop-6.2.7.jar:6.2.7]
2025-09-09T13:40:05.5991045Z 	at org.eclipse.dirigible.components.data.processes.schema.imp.tasks.ImportTableDataTask$$SpringCGLIB$$0.execute(<generated>) ~[dirigible-components-data-processes-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.5992828Z 	at org.eclipse.dirigible.components.data.processes.schema.imp.tasks.BaseImportTask.execute(BaseImportTask.java:16) ~[dirigible-components-data-processes-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.5994452Z 	at org.eclipse.dirigible.components.engine.bpm.flowable.delegate.BPMTask.executeForTenant(BPMTask.java:44) ~[dirigible-components-engine-bpm-flowable-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.5996046Z 	at org.eclipse.dirigible.components.engine.bpm.flowable.delegate.BPMTask.lambda$execute$0(BPMTask.java:29) ~[dirigible-components-engine-bpm-flowable-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.5997642Z 	at org.eclipse.dirigible.components.tenants.tenant.TenantContextImpl.execute(TenantContextImpl.java:67) ~[dirigible-components-core-tenants-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.5999118Z 	at org.eclipse.dirigible.components.tenants.tenant.TenantContextImpl.execute(TenantContextImpl.java:59) ~[dirigible-components-core-tenants-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.6000622Z 	at org.eclipse.dirigible.components.engine.bpm.flowable.delegate.BPMTask.execute(BPMTask.java:28) ~[dirigible-components-engine-bpm-flowable-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.6001829Z 	at org.flowable.engine.impl.delegate.invocation.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:35) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6002929Z 	at org.flowable.engine.impl.delegate.invocation.DelegateInvocation.proceed(DelegateInvocation.java:32) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6004150Z 	at org.flowable.engine.impl.delegate.invocation.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:26) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6005595Z 	at org.flowable.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:177) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6006981Z 	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:298) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6008171Z 	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:175) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6009368Z 	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:125) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6010568Z 	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:88) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6011682Z 	at org.flowable.common.engine.impl.AbstractEngineConfiguration.lambda$new$0(AbstractEngineConfiguration.java:196) ~[flowable-engine-common-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6012771Z 	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:169) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6013774Z 	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:124) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6014768Z 	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:78) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6015834Z 	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:26) ~[flowable-engine-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6017107Z 	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) ~[flowable-engine-common-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6018479Z 	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:105) ~[flowable-engine-common-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6019737Z 	at org.flowable.common.spring.SpringTransactionInterceptor.lambda$execute$0(SpringTransactionInterceptor.java:57) ~[flowable-spring-common-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6021000Z 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-6.2.7.jar:6.2.7]
2025-09-09T13:40:05.6022080Z 	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:57) ~[flowable-spring-common-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6023159Z 	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) ~[flowable-engine-common-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6024247Z 	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) ~[flowable-engine-common-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6025280Z 	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51) ~[flowable-engine-common-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6026430Z 	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:119) ~[flowable-job-service-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6027608Z 	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.runInternally(ExecuteAsyncRunnable.java:107) ~[flowable-job-service-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6028737Z 	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:82) ~[flowable-job-service-7.1.0.jar:7.1.0]
2025-09-09T13:40:05.6029642Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
2025-09-09T13:40:05.6030484Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
2025-09-09T13:40:05.6031054Z 	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
2025-09-09T13:40:05.6031654Z Caused by: org.postgresql.util.PSQLException: ERROR: relation "public.USERS" does not exist
2025-09-09T13:40:05.6032071Z   Position: 22
2025-09-09T13:40:05.6032661Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733) ~[postgresql-42.7.5.jar:42.7.5]
2025-09-09T13:40:05.6033578Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420) ~[postgresql-42.7.5.jar:42.7.5]
2025-09-09T13:40:05.6034428Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372) ~[postgresql-42.7.5.jar:42.7.5]
2025-09-09T13:40:05.6035231Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517) ~[postgresql-42.7.5.jar:42.7.5]
2025-09-09T13:40:05.6035959Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:434) ~[postgresql-42.7.5.jar:42.7.5]
2025-09-09T13:40:05.6037310Z 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[postgresql-42.7.5.jar:42.7.5]
2025-09-09T13:40:05.6038274Z 	at org.postgresql.jdbc.PgCallableStatement.executeWithFlags(PgCallableStatement.java:90) ~[postgresql-42.7.5.jar:42.7.5]
2025-09-09T13:40:05.6039169Z 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137) ~[postgresql-42.7.5.jar:42.7.5]
2025-09-09T13:40:05.6040152Z 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-6.3.0.jar:na]
2025-09-09T13:40:05.6041681Z 	at com.zaxxer.hikari.pool.HikariProxyCallableStatement.executeQuery(HikariProxyCallableStatement.java) ~[HikariCP-6.3.0.jar:na]
2025-09-09T13:40:05.6042852Z 	at org.eclipse.dirigible.components.data.csvim.processor.CsvimProcessor.isEmptyTable(CsvimProcessor.java:563) ~[dirigible-components-data-csvim-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.6044936Z 	at org.eclipse.dirigible.components.data.csvim.processor.CsvimProcessor.process(CsvimProcessor.java:173) ~[dirigible-components-data-csvim-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.6046355Z 	at org.eclipse.dirigible.components.data.export.service.DataImportService.importData(DataImportService.java:87) ~[dirigible-components-data-import-13.0.0-SNAPSHOT.jar:na]
2025-09-09T13:40:05.6047758Z 	at org.eclipse.dirigible.compo

* Revert "change import schema determination logic"

This reverts commit 79db3a3b71d46edd111750ac6988151c62752441.

* fix foreign keys creation - add the schema as well

* fix import schema determination logic

fix SchemaExportImportIT

* adapt test

* fix HANA export / Postgres import for the testing tables

* adapt/fix tests

* allow more cases which are supported so far in dirigible

* import schema in snowflake fixes

* support finding folders without trailing / in S3 API

fix schema export process when using S3 and the path doesn't have trailing /

* fix OOM on exporting large tables ~ 8gb

* fix OOM on importing large tables ~ 8gb with local documents

* separate tasks for export table data and store file as document

* Revert "separate tasks for export table data and store file as document"

This reverts commit 8c8566322540a163425ba58aea7f1dd766b81aba.

* handle content null - keep previous behaviour

* fix OOM issues on export/import large tables using S3 CMIS

* rollback DatabaseFacade.java

* fix codeql warnings