Fix release job
Fix release workflow 
Example failure: https://github.com/eclipse-dirigible/dirigible/actions/runs/12688097060

```
Run softprops/action-gh-release@v2
👩‍🏭 Creating new GitHub release for tag v10.6.38...
⚠️ GitHub release failed with status: 403
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release","status":"403"}
Skip retry — your GitHub token/PAT does not have the required permission to create a release
Error: Resource not accessible by integration - https://docs.github.com/rest/releases/releases#create-a-release
```

Signed-off-by: Iliyan Velichkov <velichkov.iliyan@gmail.com>